import React from 'react'
import Head from 'next/head';
import DiscoverCardList from '@/components/DiscoverCardList';
import DiscoverHero from '@/components/DiscoverHero';



export default function discover() {
    return (
        <>
            <Head>
            <title>Reflix | Discover</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            </Head>
            <DiscoverHero />
            <DiscoverCardList />
        </>
    )
}
