import Head from 'next/head';
import Hero from '@/components/Hero';
import Swipers from '@/components/swiper';
import CardList from '@/components/CardList';
import Title from '@/components/Title';
export default function Home() {
    return (
        <>
        <Head>
            <title>Reflix</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="rl.png" />
        </Head>
        <Hero />
        <Swipers />
        <Title />
        <CardList />
        </>
    )
}