import React from 'react'
import Head from 'next/head';
import PopularCardList from '@/components/PopularCardList';
import PopularHero from '@/components/PopularHero';
export default function popular() {
  return (
    <>
      <Head>
        <title>Reflix | popular</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PopularHero />
      <PopularCardList />
    </>
  )
}
