import React from 'react'
import Head from 'next/head';
import TopCardList from '@/components/TopCardList';
import TopHero from '@/components/TopHero';
export default function top() {
  return (
    <>
      <Head>
        <title>Reflix | Top</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopHero />
      <TopCardList />
    </>
  )
}