import React from 'react'
import Head from 'next/head';
import UpcomingHero from '@/components/UpcomingHero';
import UpcomingCardList from '@/components/UpcomingCardList';
export default function upcoming() {
  return (
    <>
      <Head>
        <title>Reflix | Uupcomingop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UpcomingHero />
      <UpcomingCardList />
    </>
  )
}